<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents; // Gunakan ini jika ada
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon; // Untuk timestamps

class SiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Gunakan Carbon untuk timestamp saat ini
        $now = Carbon::now();

        $siswas = [
            // Data awal yang Anda berikan
            ['nisn' => '5080', 'nama' => 'Aand Marfil Modok', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5081', 'nama' => 'Ade Arwestan Abraham', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5082', 'nama' => 'Adelci Mariance Modokh', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5083', 'nama' => 'Afril Arini Poy', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5084', 'nama' => 'AGNES MANU', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5085', 'nama' => 'AJRIL MUHAIMIN BAHARUDIN', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5086', 'nama' => 'Alan Ferdinan Lusi', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5087', 'nama' => 'Alda Henukh', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5088', 'nama' => 'Alda Tallo', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5089', 'nama' => 'Aldi Gusthino Foes', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5090', 'nama' => 'Aldi Jastision Mbuik', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5091', 'nama' => 'Aldi Melkia Elly', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5092', 'nama' => 'Alexsanderina Etman', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5093', 'nama' => 'ALFONSA DORTIANA BARBARADO MAN', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5094', 'nama' => 'Alfred Elias Mbau', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5095', 'nama' => 'Alfredo Hendrik Dethan', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5096', 'nama' => 'Alfret Julius Ndolu', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5097', 'nama' => 'Althaf Bilal Gibran Sarabiti', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5098', 'nama' => 'Altrin Putri Flisiana Bullu', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5099', 'nama' => 'ALVINIA MARDISTA MBAU', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5100', 'nama' => 'Alwan Selvester Dano', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5101', 'nama' => 'Amelda Nggily', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5102', 'nama' => 'ANANDA CLAUDIA TALLI', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5103', 'nama' => 'Anderias Lilo', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5104', 'nama' => 'ANDIKA RAHMAD SUDRAJAD ENCHO', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5105', 'nama' => 'Andre Hesron Kay', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5106', 'nama' => 'Andre Yohanis Dano', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5107', 'nama' => 'Andreas William Foes', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5108', 'nama' => 'Anisa Aryanti Saputri Tulle', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5109', 'nama' => 'Anisa Enjelina Modok', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5110', 'nama' => 'Anjes Stiber Solo', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5111', 'nama' => 'Aprilia Mesah', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5112', 'nama' => 'APRILIA PUTRI FLORENSA LOE', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5113', 'nama' => 'Aqzandro Juda Don Ngefak', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5114', 'nama' => 'Ardi Alfredo Pandie', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5115', 'nama' => 'ARDIAN JAELIS DUARJUN MOOY', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5116', 'nama' => 'ARFAN SATRIO BULAN', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5117', 'nama' => 'Ari Arjuna Fafo', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5118', 'nama' => 'Arjan Sula', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5119', 'nama' => 'Arki Nalle', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5120', 'nama' => 'Arni Elsiana Poy', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5121', 'nama' => 'Arya Yulius Henuk', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5122', 'nama' => 'Ayu Modok', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5123', 'nama' => 'Bagas Albert Suek', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5124', 'nama' => 'BALQIS AIRILA SAIBU TAHER', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5125', 'nama' => 'BERTHA ENCI NIKE', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5126', 'nama' => 'Brenli Dwi Putra Lango', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5127', 'nama' => 'Chaterine Sabrita Putry Kolly', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5128', 'nama' => 'Celsi Lidia Suek', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5129', 'nama' => 'Charles Andry Papa Saudila', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5130', 'nama' => 'CHAYUDIN RAJIU KALOMANG', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5131', 'nama' => 'Chelsea Anantha Rohi', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5132', 'nama' => 'Christine Dwiner Bullu', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5133', 'nama' => 'Cicilia Aprini Ledoh', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5134', 'nama' => 'Clarita Permata Tungga', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5135', 'nama' => 'Danielle Ester br. Panjaitan', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5136', 'nama' => 'Dario Alfandi Solumodok', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5137', 'nama' => 'Darwan Falentino Ballu', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5138', 'nama' => 'Dearly Pieter Ufi', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5139', 'nama' => 'Debi Fransiska Ndolu', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5140', 'nama' => 'Debora Foes', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5141', 'nama' => 'Devid Armanto Adu', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5142', 'nama' => 'Defri Monika Dami', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5143', 'nama' => 'Dego Armando Lani', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5144', 'nama' => 'Delvan Solo', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5145', 'nama' => 'Delvandri Dethan', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5146', 'nama' => 'Deflin Sarlince Ballu', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5147', 'nama' => 'Delni Novita Modok', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5148', 'nama' => 'Delon Rifaldi Pah', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5149', 'nama' => 'Delpiero Faot', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5150', 'nama' => 'DIMSA FOES', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5151', 'nama' => 'Demsy Gilbed Bullu', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5152', 'nama' => 'Demsi K. Dethan', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5153', 'nama' => 'Denci Juleta Fafo', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5154', 'nama' => 'Deri Glen Mboe', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5155', 'nama' => 'Desry Natalia Sopa', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5156', 'nama' => 'Desna Misellia Ndun', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5157', 'nama' => 'Desri Lorensa Modok', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5158', 'nama' => 'Desti Adriana Tallo', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5159', 'nama' => 'Destiny Oktavianus', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5160', 'nama' => 'Destrianti M. Nggolut', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5161', 'nama' => 'Dewi Anggelina Fanggi', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5162', 'nama' => 'Dewi Yusni Fora', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5163', 'nama' => 'DHIFAN ROMANSON MBOE', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5164', 'nama' => 'DIANITA NATALIA HELENA NDOLU', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5165', 'nama' => 'Difan Elimanafe', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5166', 'nama' => 'Dimas Adhyaksa Balu', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5167', 'nama' => 'Dini Nalukh', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5168', 'nama' => 'Dirvan Pandie', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5169', 'nama' => 'Diven Aryanto Modok', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5170', 'nama' => 'Dortia Bessie', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5171', 'nama' => 'Egi Nalley', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5172', 'nama' => 'Elen Adestin Ndun', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5173', 'nama' => 'Elis Ledoh', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5174', 'nama' => 'Elmar Anita Dano', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5175', 'nama' => 'Elmi Wehelmina Solumodok', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5176', 'nama' => 'ELSA BRIA', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5177', 'nama' => 'Elthon Apriyanto Dunggun', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5178', 'nama' => 'Endang Trivila Dethan', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5179', 'nama' => 'Enjela Agusti Juwita Mboe', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5180', 'nama' => 'Enos Anselmus Taneo', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5181', 'nama' => 'Eriko Guteres Adu', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5182', 'nama' => 'Ester Enjelina Forah', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5183', 'nama' => 'Exselmin Suelay Lutu', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5184', 'nama' => 'Faldarika Fek', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5185', 'nama' => 'FAMINIAR NAZWA PRATIWI', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5186', 'nama' => 'Farel Rotanja Hilli', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5187', 'nama' => 'Feliks Marsel Hanas', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5188', 'nama' => 'Fendi F. Ledoh', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5189', 'nama' => 'Fenti Natasia Lete', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5190', 'nama' => 'Fentri Loe', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5191', 'nama' => 'FERDI DEFRINTO FOES', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5192', 'nama' => 'Fernando C. Lion', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5193', 'nama' => 'Fikri Cialdi Muda', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5194', 'nama' => 'Floresita Pertiwi Hello', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5195', 'nama' => 'Fransisko Dethan', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5196', 'nama' => 'FRENGKI YAKOBIS SELU', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5197', 'nama' => 'Frit Dolin Solukh', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5198', 'nama' => 'Jeksi Galang Elimanafe', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5199', 'nama' => 'Gemas Adu', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5200', 'nama' => 'George M. H. Lengga', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5201', 'nama' => 'Gersi Apriani Ndun', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5202', 'nama' => 'Gestro Ida Dethan', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5203', 'nama' => 'Gheyrald Jehud Nomleni', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5204', 'nama' => 'GIDEN A.G MOY', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5205', 'nama' => 'Gilbert Vito Yonathan Hendrik Nullik', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5206', 'nama' => 'Gimberli Aprilia Folle', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5207', 'nama' => 'Grestin Ayujuntal Tassi', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5208', 'nama' => 'Halena Sodak', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5209', 'nama' => 'HALIMA A JAMAL', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5210', 'nama' => 'Hangry Ingamita', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5211', 'nama' => 'Heberd Gasper Tallo', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5212', 'nama' => 'Helda Winthari Muda', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5213', 'nama' => 'Hemsi Grevan Adrian P. Medah', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5214', 'nama' => 'Igalita Ndun', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5215', 'nama' => 'Imanuel Januardi Ndun', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5216', 'nama' => 'Imelda Poy', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5217', 'nama' => 'Imron Yohanis Ndun', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5218', 'nama' => 'Indah Juliwati Lani', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5219', 'nama' => 'Indra Saputra Nafi', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5220', 'nama' => 'Indri Nggili', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5221', 'nama' => 'Inggrid Carolia Triputri Naluk', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5222', 'nama' => 'Inggrid Yolsandi Modok', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5223', 'nama' => 'Ingrit Novilla Naluk', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5224', 'nama' => 'Intan Jachlin Lute', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5225', 'nama' => 'Iren Griselda Mboe', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5226', 'nama' => 'Iren Irawati Adu', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5227', 'nama' => 'Irlan Daniel Tungga', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5228', 'nama' => 'Iron B. Tungga', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5229', 'nama' => 'Irvan Bertolens Tungga', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5230', 'nama' => 'Ivonie Triana Panie', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5231', 'nama' => 'Iyen Talomanafe', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5232', 'nama' => 'JAY PAULUS MESAH', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5233', 'nama' => 'Jedianto Killok', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5234', 'nama' => 'Jefri Suprian Jes Mbau', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5235', 'nama' => 'Jelia Imelda Nalle', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5236', 'nama' => 'Jembri Imanuel Elly', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5237', 'nama' => 'Jensi Ledya Giri', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],

            // Data Lanjutan yang Anda berikan
            ['nisn' => '5238', 'nama' => 'Jesen Arianto Muda', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5239', 'nama' => 'Jesisca A. Ndolu', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5240', 'nama' => 'Jewel Granisya Nggili', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5241', 'nama' => 'Jibran Bernadus Nur Nggili', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5242', 'nama' => 'Jilma Selly', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5243', 'nama' => 'Jimmy Erikson Ani', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5244', 'nama' => 'Josmic Jolio Aditya Hello', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5245', 'nama' => 'Jovancha Ndoen', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'], // Asumsi P
            ['nisn' => '5246', 'nama' => 'JUAN DANY PRATAMA MOOY', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5247', 'nama' => 'Julingsi Herlinton Irmasari Ndolu', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5248', 'nama' => 'Julio Fua', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5249', 'nama' => 'JULISTA S. P NDUN', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5250', 'nama' => 'Junior Musdiono Tunardjo', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5251', 'nama' => 'Junli Naema Selly', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'], // Asumsi P
            ['nisn' => '5252', 'nama' => 'Juven Namo', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'], // Asumsi L
            ['nisn' => '5253', 'nama' => 'Juven Saldi Dillak', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'], // Asumsi L
            ['nisn' => '5254', 'nama' => 'Kaisar Aliosman Lanik', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5255', 'nama' => 'Karin Pestiria Ndun', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5256', 'nama' => 'Kasnila Diranti Ndun', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5257', 'nama' => 'KATRIANA MBAU', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5258', 'nama' => 'Kendri Elhemus Poy', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'], // Asumsi L
            ['nisn' => '5259', 'nama' => 'KESIA ANDRENE HENUK', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5260', 'nama' => 'Kevin Aderey Rohi', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5261', 'nama' => 'Kevin G. Luik', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5262', 'nama' => 'Lalu Faeral Anugrah', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5263', 'nama' => 'Laura Ndun', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5264', 'nama' => 'Lili Siriwangi Matasina', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5265', 'nama' => 'Liontin Viktoria Mooy', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5266', 'nama' => 'Lisda Afliana Rondo', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5267', 'nama' => 'Maikel Malelak', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5268', 'nama' => 'Malek Melike Ndun', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'], // Asumsi L (Malek)
            ['nisn' => '5269', 'nama' => 'Mardannia Alya Ananci Ledoh', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5270', 'nama' => 'Mardi  Rainard Ndun', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5271', 'nama' => 'Marlin Day', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5272', 'nama' => 'Marlin Messakh', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5273', 'nama' => 'Marni Alfi MariaLedoh', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5274', 'nama' => 'Marni Irvani Ndun', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5275', 'nama' => 'Marni Sartika Ndolu', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5276', 'nama' => 'Marsanda Delila Tungga', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5277', 'nama' => 'Marsel Fernandes Elimanafe', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5278', 'nama' => 'Marsela Audri Rohi', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5279', 'nama' => 'Marsela Ndoen', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5280', 'nama' => 'Marselino Ndun', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5281', 'nama' => 'Marten Fransius Ndun', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5282', 'nama' => 'Marton Busu', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5283', 'nama' => 'Maxwell Faren Matly', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5284', 'nama' => 'MAYA M. NGGILI', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5285', 'nama' => 'Maisandra Nayana Poy', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5286', 'nama' => 'Mexi Aleksandro Mandala', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5287', 'nama' => 'Melani Cicilia Taklael', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5288', 'nama' => 'MELIAN GRASELA ELIMANAFE', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5289', 'nama' => 'Melki Bertolens Ufi', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5290', 'nama' => 'Melfin Veronita Nullek', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5291', 'nama' => 'Mendro Obenson Fafo', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5292', 'nama' => 'Merchela Susanti Lau', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5293', 'nama' => 'Mersi Fens Nggili', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'], // Asumsi P
            ['nisn' => '5294', 'nama' => 'Mesi Botok', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'], // Asumsi P
            ['nisn' => '5295', 'nama' => 'Minto Rianto Oktovianus Adu', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5296', 'nama' => 'Miranda Ledoh', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5297', 'nama' => 'MUARIF A. MANTJORA', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5298', 'nama' => 'MUNIR SUMARJONO', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5299', 'nama' => 'Nando Aleandro Solukh', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5300', 'nama' => 'Natalia Lette', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5301', 'nama' => 'Nelson Modok', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5302', 'nama' => 'Nifrayalin Day', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'], // Asumsi P
            ['nisn' => '5303', 'nama' => 'Nikson Novendi Ndun', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5304', 'nama' => 'Nina Candra Ningsi Lete', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5305', 'nama' => 'Nindi Marlenci Seuk', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5306', 'nama' => 'Ningri Inriyati Rumatri Bell', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5307', 'nama' => 'Noven Yohanis Lanik', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5308', 'nama' => 'Olfin Dominggus Hello', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5309', 'nama' => 'Oma Naomi Pandie', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5310', 'nama' => 'Pangki Lani', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'], // Asumsi L
            ['nisn' => '5311', 'nama' => 'Preti Priskila Poy', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5312', 'nama' => 'Priella Gladis Aurelia Mooy', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5313', 'nama' => 'Prilly Heryani Nggeon', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5314', 'nama' => 'Putra Adi Bungsu Kadja', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5315', 'nama' => 'Putri Aprilia Inri Solumodok', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5316', 'nama' => 'Putri Natasya A Lia Nggili', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5317', 'nama' => 'Putri P. O. Pah', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5318', 'nama' => 'Rafli Valentino Fafo', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5319', 'nama' => 'Raliana Loranse M.Nggiri', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'], // Asumsi P
            ['nisn' => '5320', 'nama' => 'Rasni Rosliana Lani', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5321', 'nama' => 'Ratna Sari Adu', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5322', 'nama' => 'Ratna Sari Babo', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5323', 'nama' => 'Rayen Mestika Mooy', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'], // Asumsi L
            ['nisn' => '5324', 'nama' => 'RAYMONA CRISTIANI T. BAOK', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5325', 'nama' => 'Renol Gifandro Menda', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5326', 'nama' => 'Rescarly Arkilaus Hello', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5327', 'nama' => 'Reskimer Djuanda Fanggidae', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5328', 'nama' => 'Resli Febrianto Ndolu', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5329', 'nama' => 'Resti Donggi', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5330', 'nama' => 'REYNALDI PAULUS MESSAKH', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5331', 'nama' => 'Rian Rifaldi Mesah', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5332', 'nama' => 'Rijal Defrinto Hanas', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5333', 'nama' => 'Riki Marselino Selly', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5334', 'nama' => 'Rini Olivia Pah', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5335', 'nama' => 'Riomax Elimanafe', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'], // Asumsi L
            ['nisn' => '5336', 'nama' => 'RISAL YOHANIS SELU', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5337', 'nama' => 'Riski Aryanto Saudila', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5338', 'nama' => 'Risna Akdalia Solukh', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5339', 'nama' => 'RISNA PRAMESWARI NDU UFI', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5340', 'nama' => 'Ristin Selly', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5341', 'nama' => 'Rival Marten Luter Hanas', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5342', 'nama' => 'Riyanti Pandie', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5343', 'nama' => 'Roger Marfadiardo Nafi', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5344', 'nama' => 'Rohandres Irwasta Jeklian Namo', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5345', 'nama' => 'Roki Yanto nggili', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5346', 'nama' => 'Rolanda Elimanafe', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'], // Asumsi P (-a)
            ['nisn' => '5347', 'nama' => 'Roman A. Modok', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5348', 'nama' => 'Ronaldo Paulus Hello', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5349', 'nama' => 'Rosmawati Timu', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5350', 'nama' => 'Salwa Samsudin', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5351', 'nama' => 'Sandi Malven Modok', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5352', 'nama' => 'Sandi Nalle', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5353', 'nama' => 'Sandra Angelia Yuningsi Bullu', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5354', 'nama' => 'Sandra Liberti Dethan', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5355', 'nama' => 'Sandra Mandala', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5356', 'nama' => 'Sandrio Salmun Messakh', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5357', 'nama' => 'Saputra Y. Dethan', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5358', 'nama' => 'Sarlaf Jhon Friboy Dano', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5359', 'nama' => 'Sastra Anjelika Messakh', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5360', 'nama' => 'Sella Delije Juwantri Ndun', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5361', 'nama' => 'Selvi Angelia Yosinta Nenoliu', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5362', 'nama' => 'Sepryana Sa\'u', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5363', 'nama' => 'Sepsti Derliana Modok', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5364', 'nama' => 'Sesi Marwati Lete', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5365', 'nama' => 'Shangrila Modok', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'], // Asumsi P (-a)
            ['nisn' => '5366', 'nama' => 'SIFRA LOE', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5367', 'nama' => 'Sinta Yumilia Selly', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5368', 'nama' => 'Sisel Kristina Ndolu', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5369', 'nama' => 'Sofiani Lau', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5370', 'nama' => 'Sri Endang Nalle', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5371', 'nama' => 'Sri Kesia Ndu Ufi', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5372', 'nama' => 'STEFANUS GILARDINYO MOY', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5373', 'nama' => 'Stella D. F. Luik', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5374', 'nama' => 'Stela Ratnawati Selly', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5375', 'nama' => 'SULIS DAYANTI LAMISI', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5376', 'nama' => 'Suparno Talomanafe', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5377', 'nama' => 'SURYA ANTHNIOR SAKAN', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5378', 'nama' => 'Tiji Helenla Mbau', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'], // Asumsi P
            ['nisn' => '5379', 'nama' => 'Tiven Alwa Halija Ndun', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'], // Asumsi L
            ['nisn' => '5380', 'nama' => 'Trisna Yunita Ndun', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5381', 'nama' => 'Trivalny Mardini Adu', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'], // Asumsi P
            ['nisn' => '5382', 'nama' => 'Ucokh Fua', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5383', 'nama' => 'Untung Putra Yohanes Sau', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5384', 'nama' => 'Venna Ifanny Zandy Tameon', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5385', 'nama' => 'VEROBRIKA HENUK', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5386', 'nama' => 'Vista Mandala', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5387', 'nama' => 'Vivi C. Dethan', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5388', 'nama' => 'Vizca Andara Mba\'u', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5389', 'nama' => 'Forises F.D Mboe', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'], // Asumsi L
            ['nisn' => '5390', 'nama' => 'Wanda Esau Elimanafe', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'], // Asumsi L
            ['nisn' => '5391', 'nama' => 'WANDES FILMON ARYANCE TALLY', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5392', 'nama' => 'Wati Elimanafe', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5393', 'nama' => 'Wempi Leli', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5394', 'nama' => 'Wempi Nalle', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5395', 'nama' => 'Wendi Adhiyaksa Echotrio Pah', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5396', 'nama' => 'Wetri Vista Dewinta Seuhk', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5397', 'nama' => 'Wilem Yulianto Modok', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5398', 'nama' => 'Windi Marsandha Apriana Killok', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5399', 'nama' => 'Windi Naema Elimanafe', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5400', 'nama' => 'Wini Marlin Forah', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5401', 'nama' => 'Wiwi Wehelmina Nalluk', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5402', 'nama' => 'Wulandari S.M. Nggolut', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5403', 'nama' => 'Yandri Dethan', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5404', 'nama' => 'Yandi Arkiles Maku', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5405', 'nama' => 'YELVAN MELKIANUS BANDI', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5406', 'nama' => 'Yestin Feni Halia Kanuk', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5407', 'nama' => 'Yofran Lasarus Nggili', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5408', 'nama' => 'Yohana Aranci Dano', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5409', 'nama' => 'Yohnes Aguts Tungga', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5410', 'nama' => 'Yolendra Lusi', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'], // Asumsi P (-a)
            ['nisn' => '5411', 'nama' => 'Yosin Solukh', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'], // Asumsi P
            ['nisn' => '5412', 'nama' => 'Yosua Haikal Adu', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5413', 'nama' => 'YUDIT T. B. TUNGGA', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5414', 'nama' => 'Yumida Meliana Ledoh', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5415', 'nama' => 'Yunarita Ndolu', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5416', 'nama' => 'Yunel Frida Foes', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5417', 'nama' => 'Yuni Nalle', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5418', 'nama' => 'Yunior Ningsi Daniati Londa', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5419', 'nama' => 'Yustina Tera Veronika Henuk', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5420', 'nama' => 'Yusuf Octovian Messakh', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5421', 'nama' => 'RESA PANDIE', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'], // Asumsi P (Resa)
            ['nisn' => '5422', 'nama' => 'Wahyu Saudila', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'], // Asumsi L (Wahyu)
            ['nisn' => '5423', 'nama' => 'Zefanya Zakarias Mbolik', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5424', 'nama' => 'Resa A. Adu', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'], // Asumsi P (Resa)
            ['nisn' => '5425', 'nama' => 'ZUBAIR AL-FARIJIN SUNARDI BATJO', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5426', 'nama' => 'Yuningsi Angriani Foes', 'kelas' => 'XII', 'jeniskelamin' => 'Perempuan', 'alamat' => '-'],
            ['nisn' => '5427', 'nama' => 'ALFIN MAWARDI ELIMANAFE', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5428', 'nama' => 'Desri Irgonik Eko Adu', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'], // Asumsi L (Eko)
            ['nisn' => '5429', 'nama' => 'Naldi Nimrot Tallo', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5430', 'nama' => 'Nikson Dethan', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5431', 'nama' => 'Rensal Dano', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'], // Asumsi L
            ['nisn' => '5432', 'nama' => 'Rio Prianto Giri', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
            ['nisn' => '5433', 'nama' => 'Valen Day', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'], // Asumsi L (Valen)
            ['nisn' => '5434', 'nama' => 'Zaldy Aresto Naluk', 'kelas' => 'XII', 'jeniskelamin' => 'Laki-laki', 'alamat' => '-'],
        ];

        // Tambahkan timestamps ke setiap data siswa
         $dataToInsert = [];
         foreach ($siswas as $siswa) {
             $dataToInsert[] = array_merge($siswa, [
                 'created_at' => $now,
                 'updated_at' => $now,
             ]);
         }

        // Hapus data lama jika perlu sebelum insert (opsional)
        DB::table('siswas')->delete();

        // Insert data ke database
        // Gunakan insert agar lebih cepat untuk data banyak
        DB::table('siswas')->insert($dataToInsert);

        // Jika Anda ingin menggunakan Eloquent (lebih lambat untuk data banyak):
        // foreach ($siswas as $siswa) {
        //     \App\Models\Siswa::create($siswa); // Pastikan fillable di model Siswa sudah benar
        // }
    }
}